





/*************
code To be added

      /*@
        // Floating point stack

        float80_type ST0;
        float80_type ST1;
        float80_type ST2;
        float80_type ST3;
        float80_type ST4;
        float80_type ST5;
        float80_type ST6;
        float80_type ST7;

        // Floating point flags

        uint8_t FPU_FLAG_BUSY;
        uint8_t FPU_FLAG_C3;
        uint8_t FPU_FLAG_C2;
        uint8_t FPU_FLAG_C1;
        uint8_t FPU_FLAG_C0;
        uint8_t FPU_FLAG_ES;
        uint8_t FPU_FLAG_SF;
        uint8_t FPU_FLAG_PE;
        uint8_t FPU_FLAG_UE;
        uint8_t FPU_FLAG_OE;
        uint8_t FPU_FLAG_ZE;
        uint8_t FPU_FLAG_DE;
        uint8_t FPU_FLAG_IE;

      */  


**************/

