target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"
; module asm "  .file __FILE__;"
module asm "  .intel_syntax noprefix;"
module asm ";"

module asm "  .data"
module asm "  .type __mcsema_reg_state,@object;"
module asm "  .section\09.tbss,\22awT\22,@nobits;"
module asm "__mcsema_reg_state:"
module asm "  .zero 596;"
module asm "  .size __mcsema_reg_state, 100;"
module asm ";"
module asm "  .type __mcsema_stack,@object;"
module asm "  .section\09.tbss,\22awT\22,@nobits;"
module asm "__mcsema_stack:"
module asm "  .zero 1048576;"
module asm "  .size __mcsema_stack, 100;"
module asm ";"
module asm "  .text"
module asm ";"
module asm "  .globl mcsema_main;"
module asm "  .globl __mcsema_detach_ret;"
module asm ";"
module asm "  .globl __mcsema_attach_call;"
module asm "  .type __mcsema_attach_call,@function;"
module asm "__mcsema_attach_call:"
module asm "  .cfi_startproc;"
module asm "  pop QWORD PTR fs:[__mcsema_reg_state@TPOFF + 0];"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 8], rax;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 16], rbx;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 24], rcx;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 32], rdx;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 40], rsi;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 48], rdi;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 64], rbp;"
module asm "  xchg rsp, fs:[__mcsema_reg_state@TPOFF + 56];"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 532], r8;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 540], r9;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 548], r10;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 556], r11;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 564], r12;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 572], r13;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 580], r14;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 588], r15;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 260], xmm0;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 276], xmm1;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 292], xmm2;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 308], xmm3;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 324], xmm4;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 340], xmm5;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 356], xmm6;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 372], xmm7;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 388], xmm8;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 404], xmm9;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 420], xmm10;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 436], xmm11;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 452], xmm12;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 468], xmm13;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 484], xmm14;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 500], xmm15;"
module asm "  cmp rsp, 0;"
module asm "  jnz .Lhave_stack;"
module asm "  mov rsp, fs:[0];"
module asm "  lea rsp, [rsp + __mcsema_stack@TPOFF + 1048576];"
module asm ".Lhave_stack:"
module asm "  lea rdi, [rip + __mcsema_detach_ret];"
module asm "  push rdi;"
module asm "  mov rdi, fs:[0];"
module asm "  lea rdi, [rdi + __mcsema_reg_state@TPOFF];"
module asm "  jmp fs:[__mcsema_reg_state@TPOFF + 0];"
module asm ".Lfunc_end1:"
module asm "  .size __mcsema_attach_call,.Lfunc_end1-__mcsema_attach_call;"
module asm "  .cfi_endproc;"
module asm ";"
module asm "  .globl __mcsema_attach_ret;"
module asm "  .type __mcsema_attach_ret,@function;"
module asm "__mcsema_attach_ret:"
module asm "  .cfi_startproc;"
module asm "  xchg rsp, fs:[__mcsema_reg_state@TPOFF + 56];"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 8], rax;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 32], rdx;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 260], xmm0;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 16], rbx;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 64], rbp;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 564], r12;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 572], r13;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 580], r14;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 588], r15;"
module asm "  pop r15;"
module asm "  pop r14;"
module asm "  pop r13;"
module asm "  pop r12;"
module asm "  pop rbp;"
module asm "  pop rbx;"
module asm "  ret;"
module asm ".Lfunc_end2:"
module asm "  .size __mcsema_attach_ret,.Lfunc_end2-__mcsema_attach_ret;"
module asm "  .cfi_endproc;"
module asm ";"
module asm "  .globl __mcsema_attach_ret_value;"
module asm "  .type __mcsema_attach_ret_value,@function;"
module asm "__mcsema_attach_ret_value:"
module asm "  .cfi_startproc;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 8], rax;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 16], rbx;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 24], rcx;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 32], rdx;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 40], rsi;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 48], rdi;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 64], rbp;"
module asm "  xchg rsp, fs:[__mcsema_reg_state@TPOFF + 56];"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 532], r8;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 540], r9;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 548], r10;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 556], r11;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 564], r12;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 572], r13;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 580], r14;"
module asm "  mov fs:[__mcsema_reg_state@TPOFF + 588], r15;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 260], xmm0;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 276], xmm1;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 292], xmm2;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 308], xmm3;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 324], xmm4;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 340], xmm5;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 356], xmm6;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 372], xmm7;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 388], xmm8;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 404], xmm9;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 420], xmm10;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 436], xmm11;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 452], xmm12;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 468], xmm13;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 484], xmm14;"
module asm "  movdqu fs:[__mcsema_reg_state@TPOFF + 500], xmm15;"
module asm "  pop r15;"
module asm "  pop r14;"
module asm "  pop r13;"
module asm "  pop r12;"
module asm "  pop rbp;"
module asm "  pop rbx;"
module asm "  ret;"
module asm ".Lfunc_end0:"
module asm "  .size __mcsema_attach_ret_value,.Lfunc_end0-__mcsema_attach_ret_value;"
module asm "  .cfi_endproc;"
module asm ";"
module asm "  .globl __mcsema_detach_ret;"
module asm "  .type __mcsema_detach_ret,@function;"
module asm "__mcsema_detach_ret:"
module asm "  .cfi_startproc;"
module asm "  sub QWORD PTR fs:[__mcsema_reg_state@TPOFF + 56], 8;"
module asm "  mov rax, fs:[__mcsema_reg_state@TPOFF + 8];"
module asm "  mov rbx, fs:[__mcsema_reg_state@TPOFF + 16];"
module asm "  mov rcx, fs:[__mcsema_reg_state@TPOFF + 24];"
module asm "  mov rdx, fs:[__mcsema_reg_state@TPOFF + 32];"
module asm "  mov rsi, fs:[__mcsema_reg_state@TPOFF + 40];"
module asm "  mov rdi, fs:[__mcsema_reg_state@TPOFF + 48];"
module asm "  mov rbp, fs:[__mcsema_reg_state@TPOFF + 64];"
module asm "  xchg fs:[__mcsema_reg_state@TPOFF + 56], rsp;"
module asm "  mov r8, fs:[__mcsema_reg_state@TPOFF + 532];"
module asm "  mov r9, fs:[__mcsema_reg_state@TPOFF + 540];"
module asm "  mov r10, fs:[__mcsema_reg_state@TPOFF + 548];"
module asm "  mov r11, fs:[__mcsema_reg_state@TPOFF + 556];"
module asm "  mov r12, fs:[__mcsema_reg_state@TPOFF + 564];"
module asm "  mov r13, fs:[__mcsema_reg_state@TPOFF + 572];"
module asm "  mov r14, fs:[__mcsema_reg_state@TPOFF + 580];"
module asm "  mov r15, fs:[__mcsema_reg_state@TPOFF + 588];"
module asm "  movdqu xmm0, fs:[__mcsema_reg_state@TPOFF + 260];"
module asm "  movdqu xmm1, fs:[__mcsema_reg_state@TPOFF + 276];"
module asm "  movdqu xmm2, fs:[__mcsema_reg_state@TPOFF + 292];"
module asm "  movdqu xmm3, fs:[__mcsema_reg_state@TPOFF + 308];"
module asm "  movdqu xmm4, fs:[__mcsema_reg_state@TPOFF + 324];"
module asm "  movdqu xmm5, fs:[__mcsema_reg_state@TPOFF + 340];"
module asm "  movdqu xmm6, fs:[__mcsema_reg_state@TPOFF + 356];"
module asm "  movdqu xmm7, fs:[__mcsema_reg_state@TPOFF + 372];"
module asm "  movdqu xmm8, fs:[__mcsema_reg_state@TPOFF + 388];"
module asm "  movdqu xmm9, fs:[__mcsema_reg_state@TPOFF + 404];"
module asm "  movdqu xmm10, fs:[__mcsema_reg_state@TPOFF + 420];"
module asm "  movdqu xmm11, fs:[__mcsema_reg_state@TPOFF + 436];"
module asm "  movdqu xmm12, fs:[__mcsema_reg_state@TPOFF + 452];"
module asm "  movdqu xmm13, fs:[__mcsema_reg_state@TPOFF + 468];"
module asm "  movdqu xmm14, fs:[__mcsema_reg_state@TPOFF + 484];"
module asm "  movdqu xmm15, fs:[__mcsema_reg_state@TPOFF + 500];"
module asm "  ret;"
module asm ".Lfunc_end3:"
module asm "  .size __mcsema_detach_ret,.Lfunc_end3-__mcsema_detach_ret;"
module asm "  .cfi_endproc;"
module asm ";"
module asm "  .globl __mcsema_detach_call;"
module asm "  .type __mcsema_detach_call,@function;"
module asm "__mcsema_detach_call:"
module asm "  .cfi_startproc;"
module asm "  pop QWORD PTR fs:[__mcsema_reg_state@TPOFF + 0];"
module asm "  push rbx;"
module asm "  push rbp;"
module asm "  push r12;"
module asm "  push r13;"
module asm "  push r14;"
module asm "  push r15;"
module asm "  mov rbx, fs:[__mcsema_reg_state@TPOFF + 16];"
module asm "  mov rbp, fs:[__mcsema_reg_state@TPOFF + 64];"
module asm "  mov r12, fs:[__mcsema_reg_state@TPOFF + 564];"
module asm "  mov r13, fs:[__mcsema_reg_state@TPOFF + 572];"
module asm "  mov r14, fs:[__mcsema_reg_state@TPOFF + 580];"
module asm "  mov r15, fs:[__mcsema_reg_state@TPOFF + 588];"
module asm "  xchg fs:[__mcsema_reg_state@TPOFF + 56], rsp;"
module asm "  lea rax, [rip + __mcsema_attach_ret];"
module asm "  mov [rsp], rax;"
module asm "  jmp fs:[__mcsema_reg_state@TPOFF + 0];"
module asm ".Lfunc_end4:"
module asm "  .size __mcsema_detach_call,.Lfunc_end4-__mcsema_detach_call;"
module asm "  .cfi_endproc;"
module asm ";"
module asm "  .globl __mcsema_detach_call_value;"
module asm "  .type __mcsema_detach_call_value,@function;"
module asm "__mcsema_detach_call_value:"
module asm "  .cfi_startproc;"
module asm "  push rbx;"
module asm "  push rbp;"
module asm "  push r12;"
module asm "  push r13;"
module asm "  push r14;"
module asm "  push r15;"
module asm "  mov rax, fs:[__mcsema_reg_state@TPOFF + 8];"
module asm "  mov rbx, fs:[__mcsema_reg_state@TPOFF + 16];"
module asm "  mov rcx, fs:[__mcsema_reg_state@TPOFF + 24];"
module asm "  mov rdx, fs:[__mcsema_reg_state@TPOFF + 32];"
module asm "  mov rsi, fs:[__mcsema_reg_state@TPOFF + 40];"
module asm "  mov rdi, fs:[__mcsema_reg_state@TPOFF + 48];"
module asm "  mov rbp, fs:[__mcsema_reg_state@TPOFF + 64];"
module asm "  xchg fs:[__mcsema_reg_state@TPOFF + 56], rsp;"
module asm "  mov r8, fs:[__mcsema_reg_state@TPOFF + 532];"
module asm "  mov r9, fs:[__mcsema_reg_state@TPOFF + 540];"
module asm "  mov r10, fs:[__mcsema_reg_state@TPOFF + 548];"
module asm "  mov r11, fs:[__mcsema_reg_state@TPOFF + 556];"
module asm "  mov r12, fs:[__mcsema_reg_state@TPOFF + 564];"
module asm "  mov r13, fs:[__mcsema_reg_state@TPOFF + 572];"
module asm "  mov r14, fs:[__mcsema_reg_state@TPOFF + 580];"
module asm "  mov r15, fs:[__mcsema_reg_state@TPOFF + 588];"
module asm "  movdqu xmm0, fs:[__mcsema_reg_state@TPOFF + 260];"
module asm "  movdqu xmm1, fs:[__mcsema_reg_state@TPOFF + 276];"
module asm "  movdqu xmm2, fs:[__mcsema_reg_state@TPOFF + 292];"
module asm "  movdqu xmm3, fs:[__mcsema_reg_state@TPOFF + 308];"
module asm "  movdqu xmm4, fs:[__mcsema_reg_state@TPOFF + 324];"
module asm "  movdqu xmm5, fs:[__mcsema_reg_state@TPOFF + 340];"
module asm "  movdqu xmm6, fs:[__mcsema_reg_state@TPOFF + 356];"
module asm "  movdqu xmm7, fs:[__mcsema_reg_state@TPOFF + 372];"
module asm "  movdqu xmm8, fs:[__mcsema_reg_state@TPOFF + 388];"
module asm "  movdqu xmm9, fs:[__mcsema_reg_state@TPOFF + 404];"
module asm "  movdqu xmm10, fs:[__mcsema_reg_state@TPOFF + 420];"
module asm "  movdqu xmm11, fs:[__mcsema_reg_state@TPOFF + 436];"
module asm "  movdqu xmm12, fs:[__mcsema_reg_state@TPOFF + 452];"
module asm "  movdqu xmm13, fs:[__mcsema_reg_state@TPOFF + 468];"
module asm "  movdqu xmm14, fs:[__mcsema_reg_state@TPOFF + 484];"
module asm "  movdqu xmm15, fs:[__mcsema_reg_state@TPOFF + 500];"
module asm "  lea rax, [rip + __mcsema_attach_ret_value];"
module asm "  mov [rsp], rax;"
module asm "  jmp fs:[__mcsema_reg_state@TPOFF + 0];"
module asm ".Lfunc_end5:"
module asm "  .size __mcsema_detach_call_value,.Lfunc_end5-__mcsema_detach_call_value;"
module asm "  .cfi_endproc;"
module asm ";"
module asm "  .globl __mcsema_debug_get_reg_state;"
module asm "  .type __mcsema_debug_get_reg_state,@function;"
module asm "__mcsema_debug_get_reg_state:"
module asm "  .cfi_startproc;"
module asm "  mov rax, fs:[0];"
module asm "  lea rax, [rax + __mcsema_reg_state@TPOFF];"
module asm "  ret;"
module asm ".Lfunc_end6:"
module asm "  .size __mcsema_debug_get_reg_state,.Lfunc_end6-__mcsema_debug_get_reg_state;"
module asm "  .cfi_endproc;"
module asm ";"
