OPT=opt
LLVMDIS=llvm-dis
LLC=llc

UTILS_DIR="../utils"
INCLUDE_DIR=${UTILS_DIR}
RUN_SH=${UTILS_DIR}/run.sh  
loadso=../../source/build/lib/LLVMstack_deconstructor.so
#OPTSWITCH=-stack-decons 
OPTSWITCH=-ssh
#OPTSWITCH=-stack-decons -debug-only="stack_deconstructor"
#ICC=$(shell which icc)
outdir="Output/"
CC=clang
CXX=clang++


all:    clang

gcc:
	@echo " Using gcc"
	COMPILER=gcc ENTRY_FUNC=${ENTRY_FUNC} ASM_FILE=${ASM_FILE} FUNC_MAP=${FUNC_MAP} ${RUN_SH} ${PROG_PREFIX} 64
	@${MAKE} ext="gcc" run_pass 

clang:
	@echo " Using clang"
	mkdir -p ${outdir}
	COMPILER=clang ENTRY_FUNC=${ENTRY_FUNC} ASM_FILE=${ASM_FILE} INCLUDE_DIR=${INCLUDE_DIR} FUNC_MAP=${FUNC_MAP} SKIP_MCSEMA=1 bash -x ${RUN_SH} ${PROG_PREFIX} 64
	${MAKE} ext="clang" run_pass

icc:
	@echo " using icc"
	@COMPILER=icc ENTRY_FUNC=${ENTRY_FUNC} ASM_FILE=${ASM_FILE} FUNC_MAP=${FUNC_MAP} ${RUN_SH} ${PROG_PREFIX} 64
	${MAKE} ext="icc" run_pass

run_pass:
	echo "1"
	${OPT} -load=${loadso} ${OPTSWITCH} ${outdir}${PROG_PREFIX}.${ext}.ll  -o ${outdir}${PROG_PREFIX}.${ext}.trans.bc  2>  ${outdir}${PROG_PREFIX}.${ext}.pass.log 
	echo "2"
	${OPT} -O3  ${outdir}${PROG_PREFIX}.${ext}.trans.bc -o=${outdir}${PROG_PREFIX}.${ext}.trans.opt.bc
	echo "3"
	${LLVMDIS} ${outdir}${PROG_PREFIX}.${ext}.trans.bc -o ${outdir}${PROG_PREFIX}.${ext}.trans.ll
	echo "4"
	${LLVMDIS} ${outdir}${PROG_PREFIX}.${ext}.trans.opt.bc -o ${outdir}${PROG_PREFIX}.${ext}.trans.opt.ll
	echo "5"

	${MAKE} ext=${ext} run_check

run_check:
	@if diff -w -q ${outdir}${PROG_PREFIX}.${ext}.pass.log ${outdir}${PROG_PREFIX}.${ext}.pass.log.gold > /dev/null; then \
		echo "  ${PROG_PREFIX}: Transformations Passed"; rm -rf ${outdir}${PROG_PREFIX}.${ext}.pass.log ; \
	else \
		echo "  ${PROG_PREFIX}: Transformations Failed"; \
	fi
	${MAKE} run

.PHONY:run
run:
	${LLC} 	-march=x86-64 -filetype=obj -o ${outdir}${PROG_PREFIX}.${ext}.trans.lifted.o ${outdir}${PROG_PREFIX}.${ext}.trans.bc
	${CC} -m64 -I${INCLUDE_DIR} -o ${outdir}${PROG_PREFIX}.${ext}.trans.lifted.exe driver_64.c ${outdir}${PROG_PREFIX}.${ext}.trans.lifted.o
	@-echo ${STDIN_ARGS} |  ./${outdir}${PROG_PREFIX}.${ext}.trans.lifted.exe ${CMD_ARGS} > ${outdir}after.trans.out	
	@-echo ${STDIN_ARGS} |  ./${outdir}${PROG_PREFIX}.${ext}.lifted.exe ${CMD_ARGS} > ${outdir}before.trans.out	

	@if diff ${outdir}before.trans.out  ${outdir}after.trans.out  > /dev/null; then \
		echo "  ${PROG_PREFIX}: Output Passed"; \
		rm -rf ${outdir}*.exe ; rm -rf ${outdir}${PROG_PREFIX}.${ext}.trans.lifted.o ; rm -rf ${outdir}${PROG_PREFIX}.${ext}.trans.opt.bc ; rm -rf ${outdir}${PROG_PREFIX}.${ext}.trans.bc ${outdir}after.trans.out ; \
	else \
		echo "  ${PROG_PREFIX}: Output Failed"; \
	fi 

clean:
	@../utils/clearall.sh
	@rm -rf log *.dot *.mod



